---
# tasks file for users
- name: "Create user accounts"
  user:
    name: "{{ item }}"
    groups: "wheel"
  with_items: "{{ users }}"
- name: "Add authorized keys"
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
  with_items: "{{ users }}"
- name: "Allow wheel group to sudo without a password"
  lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"